# Default values for groom.
replicaCount: 1

# Default nginx image while components aren't ready
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80

resources: {}

rabbitmq:
  # values for rabbitmq can be found here:
  # https://github.com/kubernetes/charts/tree/master/stable/rabbitmq
  persistence:
    # Unsafe, but easier to deploy
    enabled: false
