sudo: required
language: python
services:
  - docker

stages:
  - deploy

python:
- '3.6'
install: pip install -r docs/requirements.txt
jobs:
  include:
  - stage: deploy
    script: bash .travis/deploy_docs.sh
    env:
    - ENCRYPTION_LABEL: d2b4ebb4158b
    - COMMIT_AUTHOR_EMAIL: "germain.gau@gmail.com"
    on:
      branch: develop

  - stage: deploy
    script: bash .travis/deploy_server-store.sh
