language: python
python:
- '3.6'
install: pip install -r docs/requirements.txt
jobs:
  include:
  - stage: deploy
    script: bash .travis/deploy_docs.sh
    env:
    - ENCRYPTION_LABEL: d2b4ebb4158b
    - COMMIT_AUTHOR_EMAIL: "germain.gau@gmail.com"
    on:
      branch: master
    # openssl aes-256-cbc -K $encrypted_d2b4ebb4158b_key -iv $encrypted_d2b4ebb4158b_iv -in github_deploy_key.enc -out github_deploy_key -d
