site_name: Groom
site_description: Groom orchestrate and expose ephemeral application deployments on top of Kubernetes.
site_author: Germain GAU

theme: 'material'
docs_dir: ./docs/pages
pages:
  - Index: index.md
  - Roadmap: roadmap.md
  - Architecture: architecture.md

repo_url: https://github.com/Xide/groom
markdown_extensions:
  # For notes and stuff: http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  # Noices code blocks : http://squidfunk.github.io/mkdocs-material/extensions/codehilite/
  - codehilite

  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
